### ISSUE TITLE
Spread the vimrc

### ISSUE THREAD

**Issue by pocomane** [tpope/vim-pathogen#161]
Hi, this is sort of feature request; and I am a sort of vim newbie, so I do not know if the fallowing is archivable with some vim default configuration. If so, sorry, I searched for it but I could not find anything.

I would like to split my vimrc configuration across several personal plugin, but it seems to me that some code must to be loaded at  "Vimrc time" (e.g. the viminfo path option, or some plugin configuration). My solution is very simple. I placed in my vimrc, just after the pathogen#infect, something that automatically "Include" all the files like "bundle/pluginname/autoload/pluginname_auto.vim":
```
 for path in split(&runtimepath, ',')
  let the_file_name = fnamemodify(path, ":t") . "_auto"
  if filereadable(path . "/autoload/" . the_file_name . ".vim")
    execute "call " . the_file_name . "#include()"
  endif
endfor
```
Are you planning to add to pathogen some features like this? (I know that there could be some compatibility issues with other plugin manager...)

**Comment by tpope** [comment]
At this time I don't think the handful of use cases this would support justifies inventing a proprietary pathogen standard, no. If I ever did go down this road, I would just source a broad file glob (e.g., `runtime! preload/*.vim`), rather than dictate some weird autoload function convention. All your 6 line solution adds is more boilerplate and longer, more opaque error messages.
