### ISSUE TITLE
Plugin takes 3-6 seconds to load via pathogen

### ISSUE THREAD

**Issue by fluffynuts** [tpope/vim-pathogen#196]
Referencing https://github.com/wakatime/vim-wakatime/issues/60, when loading the `vim-wakatime` plugin via pathogen, vim takes an extra 3-6 seconds to start up. If I move the plugin out of `bundle` and manually load with:
```
" .... at the end of my .vimrc
execute pathogen#infect()
source ~/vimfiles/bundle/disabled/vim-wakatime/plugin/wakatime.vim
```
Then loading times for the `vim-wakatime` plugin drop back down to around 2ms.

**Comment by tpope** [comment]
I spy use of the Python interface. My guess is it's somewhere in that black box.

**Comment by fluffynuts** [comment]
It's interesting that even if I remove the main .vim file, it still takes that amount of time to load (though, of course, the actual plugin isn't functional).

**Comment by alanhamlett** [comment]
It's because Vim is scanning every file in the `vim-wakatime/plugin/packages/` folder on startup. I think `autoload` folders are the only exception?

I've moved `vim-wakatime/plugin/packages` to `vim-wakatime/autoload/packages` with wakatime/vim-wakatime@ce51332a08725f5bd1dae48aed5e062d83d56f24, maybe this will speed things up.

**Comment by tpope** [comment]
I think that's only true of the `plugin/` directory; you could move `packages/` up to the top and be fine too.
