### ISSUE TITLE
pathogen not loading bundles - clean install

### ISSUE THREAD

**Issue by hjwp** [tpope/vim-pathogen#83]
Hi there, I have pathogen working fine on two systems, but it's not playing nice with my third.

I decided to try starting out with a completely fresh install.  It looks like pathogen itself is loading ok (I can get `:Helptags`), but it won't load any bundles (I've added vim-sensible, but it doesn't seem to get loaded -- `set incsearch?` returns `noincsearch`).

```
14:17 ~ $ cat .vimrc
set nocompatible
call pathogen#infect()
syntax on
filetype plugin indent on

14:19 ~ $ tree .vim
.vim
├── autoload
│   └── pathogen.vim
└── bundle
    └── vim-sensible
        ├── README.markdown
        └── plugin
            └── sensible.vim
```

runtimepath is `runtimepath=~/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim72,/usr/share/vim/vimfiles/after,~/.vim/after`

Any debugging suggestions?

**Comment by edbrannin** [comment]
For posterity: I was having this problem too, and it was because I wrongly expected pathogen to expand environment variables in its argument.

Broken:
`  call pathogen#infect('$DOTFILES/vim/bundle/{}')`

Working:
`  call pathogen#infect($DOTFILES.'/vim/bundle/{}')`

**Comment by tpope** [comment]
Globbing does expand environment variables so that should work. I use it in my own setup.

**Comment by edbrannin** [comment]
Actually, that would explain why it ever worked on my Mac -- but perhaps the glob syntax is system-dependent?

I should have mentioned in my previous comment that "$DOTFILES" wasn't getting expanded in Windows.

**Comment by tpope** [comment]
Oh, huh, that's surprising but not *that* surprising. Does `expand('$DOTFILES')` work as expected on Windows? If so we can leverage that to make it work consistently across platforms.

**Comment by edbrannin** [comment]
I'll check on Monday.

**Comment by edbrannin** [comment]
```
:echo Pathogen#expand('$DOTFILES')
['$DOTFILES']
:echo expand('$DOTFILES')
c:\dev\dotfiles
```

**Comment by tpope** [comment]
Alright, just to be 100% clear, what does `:echo glob('$DOTFILES')` report?

**Comment by edbrannin** [comment]
```
:echo glob('$DOTFILES')
c:\dev\dotfiles
```

**Comment by tpope** [comment]
Oh, then that my refutes my hypothesis of what was going wrong. Can you clarify ""`$DOTFILES` wasn't getting expanded in Windows", keeping in mind that `pathogen#expand()` *does not* expand environment variables?

**Comment by edbrannin** [comment]
I said "wasn't getting expanded in windows" because calling `#infect` with a string that starts with `$DOTFILES` does not cause my bundles to load.

(To add to my confusion, At some point before arriving at `pathogen#infect($DOTFILES.'/vim/bundle/{}')` I managed to get a runtimepath with several of entries like `c:\dev\dotfiles\$dotfiles\vim\bundle\...` that didn't resolve properly.  I'm not sure what caused that one.)


### Steps to reproduce:

1. `call pathogen#infect('$DOTFILES/vim/bundle/{}')`
2. `redir @a | set runtimepath | redir END | normal "ap`

### Observed Result:
`runtimepath=C:\dev\dotfiles/vim,H:\vimfiles,C:\Program Files (x86)\Vim/vimfiles,C:\Program Files (x86)\Vim\vim74,C:\Program Files (x86)\Vim/vimfiles/after,H:\vimfiles/after,C:\dev\dotfiles/vim/after,~/`

### Expected result:

(This is what I get if I call `pathogen#infect($DOTFILES.'/vim/bundle/{}')` in Step 1.)
  `runtimepath=C:\dev\dotfiles\vim\bundle\abolish,C:\dev\dotfiles\vim\bundle\ack,C:\dev\dotfiles\vim\bundle\confluencewiki.vim,C:\dev\dotfiles\vim\bundle\dwm.vim,C:\dev\dotfiles\vim\bundle\gundo.vim,C:\dev\dotfiles\vim\bundle\html-match-tag,C:\dev\dotfiles\vim\bundle\jinja2,C:\dev\dotfiles\vim\bundle\kwbdi,C:\dev\dotfiles\vim\bundle\markdown-preview,C:\dev\dotfiles\vim\bundle\matchit,C:\dev\dotfiles\vim\bundle\nerdcommenter,C:\dev\dotfiles\vim\bundle\nerdtree,C:\dev\dotfiles\vim\bundle\puppet,C:\dev\dotfiles\vim\bundle\robotframework.vim,C:\dev\dotfiles\vim\bundle\simplenote.vim,C:\dev\dotfiles\vim\bundle\snipmate.vim,C:\dev\dotfiles\vim\bundle\sparkup,C:\dev\dotfiles\vim\bundle\tabular,C:\dev\dotfiles\vim\bundle\taskpaper.vim,C:\dev\dotfiles\vim\bundle\vagrant-vim,C:\dev\dotfiles\vim\bundle\vim-colors-solarized,C:\dev\dotfiles\vim\bundle\vim-commentary,C:\dev\dotfiles\vim\bundle\vim-easymotion,C:\dev\dotfiles\vim\bundle\vim-indent-guides,C:\dev\dotfiles\vim\bundle\vim-indent-object,C:\dev\dotfiles\vim\bundle\vim-javascrip
`

(Truncated because apparently too long for vim to display them all.  I can tell more bundles than shown are loaded because vim-surround still works.)

**Comment by wamoyo** [comment]
Sorry, I'm a little (a lot) late on this, @dlukes. Hope you've managed to resolve the issue. My vim install has been super stable. It's been really consistent : )

**Comment by tpope** [comment]
Can you try `call pathogen#surround("$DOTFILES/vim/bundle/{}")` in your vimrc and see if that fails the same way?

**Comment by edbrannin** [comment]
No improvement when doing any of the following:

1. `call pathogen#surround("$DOTFILES/vim/bundle/{}")` in vimrc instead of `pathogen#infect`
2. Call `pathogen#surround` in ex mode with a thus-broken vimrc
3. Call `pathogen#infect` after step 2

This works:
* `call pathogen#surround($DOTFILES."/vim/bundle/{}")`

**Comment by tpope** [comment]
Okay, one last thing (hopefully). Can you try with a `~/something/{}` path and see if the `~` is correctly expanded to your home directory?

**Comment by tpope** [comment]
Finally dug in on Windows myself. @edbrannin, can you confirm the latest fixes it?
